{{- if .Values.stac.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "eoapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: stac
    app: {{ .Release.Name }}-stac
    gitsha: {{ .Values.gitSha }}
  name: {{ .Release.Name }}-stac
  {{- if .Values.stac.annotations }}
  annotations:
    {{- with .Values.stac.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "eoapi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: stac
      app: {{ .Release.Name }}-stac
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/services/stac/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "eoapi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: stac
        app: {{ .Release.Name }}-stac
        {{- with .Values.stac.settings.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "eoapi.pgstacInitContainers" . | nindent 6 }}
      containers:
      - image: {{ .Values.stac.image.name }}:{{ .Values.stac.image.tag }}
        name: stac
        command:
          {{- toYaml .Values.stac.command | nindent 10 }}
          {{- if (and (.Values.ingress.className) (or (eq .Values.ingress.className "nginx") (eq .Values.ingress.className "traefik"))) }}
          - "--proxy-headers"
          - "--forwarded-allow-ips=*"
          {{- if and (hasKey .Values.stac "overrideRootPath") (ne .Values.stac.overrideRootPath "") }}
          - "--root-path={{ .Values.stac.overrideRootPath }}"
          {{- else }}
          - "--root-path={{ .Values.stac.ingress.path }}"
          {{- end }}
          {{- end }}{{/* needed for proxies and path rewrites on NLB */}}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
          failureThreshold: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            {{- if hasKey .Values.stac "overrideRootPath" }}
            {{- if ne .Values.stac.overrideRootPath "" }}
            path: {{ .Values.stac.overrideRootPath }}/_mgmt/ping
            {{- else }}
            path: /_mgmt/ping
            {{- end }}
            {{- else}}
            path: /_mgmt/ping
            {{- end}}
            port: {{ .Values.service.port }}
          failureThreshold: 3
          periodSeconds: 15
          successThreshold: 1
        startupProbe:
          httpGet:
            {{- if hasKey .Values.stac "overrideRootPath" }}
            {{- if ne .Values.stac.overrideRootPath "" }}
            path: {{ .Values.stac.overrideRootPath }}/_mgmt/ping
            {{- else }}
            path: /_mgmt/ping
            {{- end }}
            {{- else}}
            path: /_mgmt/ping
            {{- end}}
            port: {{ .Values.service.port }}
          # check every sec for 1 minute
          periodSeconds: 1
          failureThreshold: 60
          successThreshold: 1
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.stac.settings.resources | nindent 10 }}
        env:
          {{- include "eoapi.postgresqlEnv" . | nindent 10 }}
          {{- include "eoapi.commonEnvVars" (dict "service" "stac" "root" .) | nindent 10 }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-stac-envvar-configmap
          {{- if .Values.stac.settings.extraEnvFrom }}
          {{- toYaml .Values.stac.settings.extraEnvFrom | nindent 10 }}
          {{- end }}
        {{- include "eoapi.mountServiceSecrets" (dict "service" "stac" "root" .) | nindent 10 }}
        {{- with .Values.stac.settings.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        {{- with .Values.stac.settings.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "eoapi.serviceAccountName" . }}
      {{- with .Values.stac.settings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stac.settings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
