{{- if .Values.browser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-browser
  labels:
    app: {{ .Release.Name }}-browser
    gitsha: {{ .Values.gitSha }}
spec:
  replicas: {{ .Values.browser.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-browser
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-browser
    spec:
      containers:
        - name: browser
          image: {{ .Values.browser.image.name }}:{{ .Values.browser.image.tag }}
          ports:
          - containerPort: 8080
          env:
            - name: SB_catalogUrl
              value: "http://{{ .Values.ingress.host }}{{ .Values.stac.ingress.path }}"
            {{- if index .Values "stac-auth-proxy" "enabled" }}
            - name: SB_authConfig
              {{- if .Values.browser.authConfig }}
              value: {{ .Values.browser.authConfig }}
              {{- else }}
              value: |
                {
                  "type": "openIdConnect",
                  "openIdConnectUrl": "{{ index .Values "stac-auth-proxy" "env" "OIDC_DISCOVERY_URL" }}",
                  "oidcOptions": {
                    "client_id": "{{ .Values.browser.oidcClientId | default "test-client" }}"
                  }
                }
              {{- end }}
            {{- end }}
{{- end }}
