{{- if .Values.browser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-browser
  labels:
    app: {{ .Release.Name }}-browser
  {{- if .Values.browser.annotations }}
  annotations:
    {{- with .Values.browser.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}-browser
  ports:
    - protocol: TCP
      port: {{ .Values.browser.service.port | default 8080 }}
      targetPort: {{ .Values.browser.service.port | default 8080 }}
{{- end }}
