{{/*
Helper template for generating ingress paths
*/}}
{{- define "eoapi.ingressPaths" -}}
{{- $stacPath := "" -}}
{{- if and .Values.stac.enabled (or (not (hasKey .Values.stac "ingress")) .Values.stac.ingress.enabled) -}}
{{- $stacPath = .Values.stac.ingress.path -}}
{{- end -}}
{{- $isNginx := eq .Values.ingress.className "nginx" -}}

{{- if and .Values.stac.enabled (or (not (hasKey .Values.stac "ingress")) .Values.stac.ingress.enabled) }}
- pathType: {{ if and $isNginx (ne $stacPath "/") }}ImplementationSpecific{{ else }}Prefix{{ end }}
  path: {{ $stacPath }}{{ if and $isNginx (ne $stacPath "/") }}(/|$)(.*){{ end }}
  backend:
    service:
      {{- if index .Values "stac-auth-proxy" "enabled" }}
      name: {{ .Release.Name }}-stac-auth-proxy
      {{- else }}
      name: {{ .Release.Name }}-stac
      {{- end }}
      port:
        number: {{ .Values.service.port }}
{{- end }}

{{- if and .Values.raster.enabled (or (not (hasKey .Values.raster "ingress")) .Values.raster.ingress.enabled) }}
- pathType: {{ if $isNginx }}ImplementationSpecific{{ else }}Prefix{{ end }}
  path: {{ .Values.raster.ingress.path }}{{ if $isNginx }}(/|$)(.*){{ end }}
  backend:
    service:
      name: {{ .Release.Name }}-raster
      port:
        number: {{ .Values.service.port }}
{{- end }}

{{- if and .Values.vector.enabled (or (not (hasKey .Values.vector "ingress")) .Values.vector.ingress.enabled) }}
- pathType: {{ if $isNginx }}ImplementationSpecific{{ else }}Prefix{{ end }}
  path: {{ .Values.vector.ingress.path }}{{ if $isNginx }}(/|$)(.*){{ end }}
  backend:
    service:
      name: {{ .Release.Name }}-vector
      port:
        number: {{ .Values.service.port }}
{{- end }}

{{- if and .Values.multidim.enabled (or (not (hasKey .Values.multidim "ingress")) .Values.multidim.ingress.enabled) }}
- pathType: {{ if $isNginx }}ImplementationSpecific{{ else }}Prefix{{ end }}
  path: {{ .Values.multidim.ingress.path }}{{ if $isNginx }}(/|$)(.*){{ end }}
  backend:
    service:
      name: {{ .Release.Name }}-multidim
      port:
        number: {{ .Values.service.port }}
{{- end }}

{{- if and .Values.testing.mockOidcServer.enabled .Values.testing.mockOidcServer.ingress.enabled }}
- pathType: {{ if $isNginx }}ImplementationSpecific{{ else }}Prefix{{ end }}
  path: {{ .Values.testing.mockOidcServer.ingress.path }}{{ if $isNginx }}(/|$)(.*){{ end }}
  backend:
    service:
      name: {{ .Release.Name }}-mock-oidc-server
      port:
        number: {{ .Values.testing.mockOidcServer.service.port | default 8080 }}
{{- end }}

{{- if and .Values.browser.enabled (or (not (hasKey .Values.browser "ingress")) .Values.browser.ingress.enabled) }}
- pathType: {{ if $isNginx }}ImplementationSpecific{{ else }}Prefix{{ end }}
  path: {{ .Values.browser.ingress.path | default "/browser" }}{{ if $isNginx }}(/|$)(.*){{ end }}
  backend:
    service:
      name: {{ .Release.Name }}-browser
      port:
        number: {{ .Values.browser.service.port | default 8080 }}
{{- end }}

{{- if .Values.docServer.enabled }}
- pathType: Prefix
  path: "/{{ .Values.ingress.rootPath | default "" }}"
  backend:
    service:
      name: {{ .Release.Name }}-doc-server
      port:
        number: 80
{{- end }}
{{- end }}

{{- $hasEnabledService := or
  (and .Values.stac.enabled (or (not (hasKey .Values.stac "ingress")) .Values.stac.ingress.enabled))
  (and .Values.raster.enabled (or (not (hasKey .Values.raster "ingress")) .Values.raster.ingress.enabled))
  (and .Values.vector.enabled (or (not (hasKey .Values.vector "ingress")) .Values.vector.ingress.enabled))
  (and .Values.multidim.enabled (or (not (hasKey .Values.multidim "ingress")) .Values.multidim.ingress.enabled))
  (and .Values.testing.mockOidcServer.enabled .Values.testing.mockOidcServer.ingress.enabled)
  (and .Values.browser.enabled (or (not (hasKey .Values.browser "ingress")) .Values.browser.ingress.enabled))
  .Values.docServer.enabled
}}
{{- if and .Values.ingress.enabled $hasEnabledService }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-ingress
  annotations:
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Release.Name }}-strip-prefix-middleware@kubernetescrd
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- include "eoapi.ingressPaths" $ | nindent 10 }}
    {{- end }}
    {{- else }}
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          {{- include "eoapi.ingressPaths" . | nindent 10 }}
    {{- end }}
  {{- if and .Values.ingress.tls.enabled (or .Values.ingress.hosts .Values.ingress.host) }}
  tls:
    - hosts:
        {{- if .Values.ingress.hosts }}
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
        {{- else if .Values.ingress.host }}
        - {{ .Values.ingress.host }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
