{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-ingress
  annotations:
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
    {{- end }}
    # Temporary annotations for Traefik until uvicorn support real prefix in ASGI: https://github.com/encode/uvicorn/discussions/2490
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-{{ $.Release.Name }}-strip-prefix-middleware@kubernetescrd
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- if and $.Values.raster.enabled (or (not (hasKey $.Values.raster "ingress")) $.Values.raster.ingress.enabled) }}
          - pathType: {{ if eq $.Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ $.Values.raster.ingress.path }}{{ if eq $.Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ $.Release.Name }}-raster
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}

          {{- if and $.Values.stac.enabled (or (not (hasKey $.Values.stac "ingress")) $.Values.stac.ingress.enabled) }}
          - pathType: {{ if eq $.Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ $.Values.stac.ingress.path }}{{ if eq $.Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                {{- if index $.Values "stac-auth-proxy" "enabled" }}
                name: {{ $.Release.Name }}-stac-auth-proxy
                {{- else }}
                name: {{ $.Release.Name }}-stac
                {{- end }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}

          {{- if and $.Values.vector.enabled (or (not (hasKey $.Values.vector "ingress")) $.Values.vector.ingress.enabled) }}
          - pathType: {{ if eq $.Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ $.Values.vector.ingress.path }}{{ if eq $.Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ $.Release.Name }}-vector
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}

          {{- if and $.Values.multidim.enabled (or (not (hasKey $.Values.multidim "ingress")) $.Values.multidim.ingress.enabled) }}
          - pathType: {{ if eq $.Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ $.Values.multidim.ingress.path }}{{ if eq $.Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ $.Release.Name }}-multidim
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}

          {{- if and $.Values.mockOidcServer.enabled $.Values.mockOidcServer.ingress.enabled }}
          - pathType: {{ if eq $.Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ $.Values.mockOidcServer.ingress.path }}{{ if eq $.Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ $.Release.Name }}-mock-oidc-server
                port:
                  number: {{ $.Values.mockOidcServer.service.port | default 8080 }}
          {{- end }}

          {{- if $.Values.docServer.enabled }}
          - pathType: Prefix
            path: "/{{ $.Values.ingress.rootPath | default "" }}"
            backend:
              service:
                name: {{ $.Release.Name }}-doc-server
                port:
                  number: 80
          {{- end }}
    {{- end }}
    {{- else }}
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          {{- if and .Values.raster.enabled (or (not (hasKey .Values.raster "ingress")) .Values.raster.ingress.enabled) }}
          - pathType: {{ if eq .Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ .Values.raster.ingress.path }}{{ if eq .Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ .Release.Name }}-raster
                port:
                  number: {{ .Values.service.port }}
          {{- end }}

          {{- if and .Values.stac.enabled (or (not (hasKey .Values.stac "ingress")) .Values.stac.ingress.enabled) }}
          - pathType: {{ if eq .Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ .Values.stac.ingress.path }}{{ if eq .Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                {{- if index .Values "stac-auth-proxy" "enabled" }}
                name: {{ .Release.Name }}-stac-auth-proxy
                {{- else }}
                name: {{ .Release.Name }}-stac
                {{- end }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}

          {{- if and .Values.vector.enabled (or (not (hasKey .Values.vector "ingress")) .Values.vector.ingress.enabled) }}
          - pathType: {{ if eq .Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ .Values.vector.ingress.path }}{{ if eq .Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ .Release.Name }}-vector
                port:
                  number: {{ .Values.service.port }}
          {{- end }}

          {{- if and .Values.multidim.enabled (or (not (hasKey .Values.multidim "ingress")) .Values.multidim.ingress.enabled) }}
          - pathType: {{ if eq .Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ .Values.multidim.ingress.path }}{{ if eq .Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ .Release.Name }}-multidim
                port:
                  number: {{ .Values.service.port }}
          {{- end }}

          {{- if and .Values.mockOidcServer.enabled .Values.mockOidcServer.ingress.enabled }}
          - pathType: {{ if eq .Values.ingress.className "nginx" }}ImplementationSpecific{{ else }}Prefix{{ end }}
            path: {{ .Values.mockOidcServer.ingress.path }}{{ if eq .Values.ingress.className "nginx" }}(/|$)(.*){{ end }}
            backend:
              service:
                name: {{ .Release.Name }}-mock-oidc-server
                port:
                  number: {{ .Values.mockOidcServer.service.port | default 8080 }}
          {{- end }}

          {{- if .Values.docServer.enabled }}
          - pathType: Prefix
            path: "/{{ $.Values.ingress.rootPath | default "" }}"
            backend:
              service:
                name: {{ .Release.Name }}-doc-server
                port:
                  number: 80
          {{- end }}
    {{- end }}
  {{- if and .Values.ingress.tls.enabled (or .Values.ingress.hosts .Values.ingress.host) }}
  tls:
    - hosts:
        {{- if .Values.ingress.hosts }}
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
        {{- else if .Values.ingress.host }}
        - {{ .Values.ingress.host }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
