{{- if .Values.vector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "eoapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
    app: {{ .Release.Name }}-vector
    gitsha: {{ .Values.gitSha }}
  name: {{ .Release.Name }}-vector
  {{- if .Values.vector.annotations }}
  annotations:
    {{- with .Values.vector.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "eoapi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vector
      app: {{ .Release.Name }}-vector
  template:
    metadata:
      labels:
        {{- include "eoapi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vector
        app: {{ .Release.Name }}-vector
        {{- with .Values.vector.settings.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "eoapi.pgstacInitContainers" . | nindent 6 }}
      containers:
      - image: {{ .Values.vector.image.name }}:{{ .Values.vector.image.tag }}
        name: vector
        command:
          {{- toYaml .Values.vector.command | nindent 10 }}
          {{- if (and (.Values.ingress.className) (or (eq .Values.ingress.className "nginx") (eq .Values.ingress.className "traefik"))) }}
          - "--proxy-headers"
          - "--forwarded-allow-ips=*"
          {{- if .Values.vector.overrideRootPath}}
          - "--root-path={{ .Values.vector.overrideRootPath }}"
          {{- else }}
          - "--root-path={{ .Values.vector.ingress.path }}"
          {{- end }}
          {{- end }}{{/* needed for proxies and path rewrites on NLB */}}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
          failureThreshold: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            {{- if .Values.vector.overrideRootPath}}
            path: {{ .Values.vector.overrideRootPath }}/healthz
            {{- else}}
            path: /healthz
            {{- end}}
            port: {{ .Values.service.port }}
          failureThreshold: 3
          periodSeconds: 15
          successThreshold: 1
        startupProbe:
          httpGet:
            {{- if .Values.vector.overrideRootPath}}
            path: {{ .Values.vector.overrideRootPath }}/healthz
            {{- else}}
            path: /healthz
            {{- end}}
            port: {{ .Values.service.port }}
          # check every sec for 1 minute
          periodSeconds: 1
          failureThreshold: 60
          successThreshold: 1
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.vector.settings.resources | nindent 10 }}
        env:
          {{- include "eoapi.postgresqlEnv" . | nindent 10 }}
          {{- include "eoapi.commonEnvVars" (dict "service" "vector" "root" .) | nindent 10 }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-vector-envvar-configmap
          {{- if .Values.vector.settings.extraEnvFrom }}
          {{- toYaml .Values.vector.settings.extraEnvFrom | nindent 10 }}
          {{- end }}
        {{- include "eoapi.mountServiceSecrets" (dict "service" "vector" "root" .) | nindent 10 }}
        {{- with .Values.vector.settings.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        {{- with .Values.vector.settings.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "eoapi.serviceAccountName" . }}
      {{- with .Values.vector.settings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vector.settings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
